import { MappedCountry } from 'types';

export const mappedCountries: MappedCountry[] = [
  {
    id: 'id',
    name: 'Afghanistan',
    capital: 'Kabul',
    alpha2Code: 'AF',
    region: 'Asia',
    population: 27657145,
    flag: 'https://restcountries.eu/data/afg.svg',
  },
  {
    id: 'id',
    name: 'Åland Islands',
    capital: 'Mariehamn',
    alpha2Code: 'AX',
    region: 'Europe',
    population: 28875,
    flag: 'https://restcountries.eu/data/ala.svg',
  },
  {
    id: 'id',
    name: 'Afghanistan',
    capital: 'Kabul',
    alpha2Code: 'AF',
    region: 'Asia',
    population: 27657145,
    flag: 'https://restcountries.eu/data/afg.svg',
  },
  {
    id: 'id',
    name: 'Åland Islands',
    capital: 'Mariehamn',
    alpha2Code: 'AX',
    region: 'Europe',
    population: 28875,
    flag: 'https://restcountries.eu/data/ala.svg',
  },
  {
    id: 'id',
    name: 'Afghanistan',
    capital: 'Kabul',
    alpha2Code: 'AF',
    region: 'Asia',
    population: 27657145,
    flag: 'https://restcountries.eu/data/afg.svg',
  },
  {
    id: 'id',
    name: 'Åland Islands',
    capital: 'Mariehamn',
    alpha2Code: 'AX',
    region: 'Europe',
    population: 28875,
    flag: 'https://restcountries.eu/data/ala.svg',
  },
  {
    id: 'id',
    name: 'Afghanistan',
    capital: 'Kabul',
    alpha2Code: 'AF',
    region: 'Asia',
    population: 27657145,
    flag: 'https://restcountries.eu/data/afg.svg',
  },
  {
    id: 'id',
    name: 'Åland Islands',
    capital: 'Mariehamn',
    alpha2Code: 'AX',
    region: 'Europe',
    population: 28875,
    flag: 'https://restcountries.eu/data/ala.svg',
  },
  {
    id: 'id',
    name: 'Afghanistan',
    capital: 'Kabul',
    alpha2Code: 'AF',
    region: 'Asia',
    population: 27657145,
    flag: 'https://restcountries.eu/data/afg.svg',
  },
  {
    id: 'id',
    name: 'Åland Islands',
    capital: 'Mariehamn',
    alpha2Code: 'AX',
    region: 'Europe',
    population: 28875,
    flag: 'https://restcountries.eu/data/ala.svg',
  },
  {
    id: 'id',
    name: 'Afghanistan',
    capital: 'Kabul',
    alpha2Code: 'AF',
    region: 'Asia',
    population: 27657145,
    flag: 'https://restcountries.eu/data/afg.svg',
  },
  {
    id: 'id',
    name: 'Åland Islands',
    capital: 'Mariehamn',
    alpha2Code: 'AX',
    region: 'Europe',
    population: 28875,
    flag: 'https://restcountries.eu/data/ala.svg',
  },
];
